export enum SyntheticsVisions {
	Intro = "Intro",
	Menu = "Menu",
	TheBitBallet = "TheBitBallet",
	NullPointerException = "NullPointerException",
	GlitchWorld = "GlitchWorld",
	EncryptedNode = "EncryptedNode",
	Gallery = "Gallery",
	CiudadSinRecuerdos = "CiudadSinRecuerdos",
	Opera = "Opera",
	OperaScene1 = "OperaScene1",
	OperaScene2 = "OperaScene2",
	OperaScene3 = "OperaScene3",
	OperaScene4 = "OperaScene4",
}